// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/embvr.h"
#include <Rcpp.h>

using namespace Rcpp;

// embv
Rcpp::List embv(t_individual individual, t_positions positions, t_effects effects, const int n_gam, const double se_level, const int min_rep, const int max_rep, const int m, const double p, Rcpp::Nullable<Rcpp::IntegerVector> seed);
RcppExport SEXP embvr_embv(SEXP individualSEXP, SEXP positionsSEXP, SEXP effectsSEXP, SEXP n_gamSEXP, SEXP se_levelSEXP, SEXP min_repSEXP, SEXP max_repSEXP, SEXP mSEXP, SEXP pSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< t_individual >::type individual(individualSEXP);
    Rcpp::traits::input_parameter< t_positions >::type positions(positionsSEXP);
    Rcpp::traits::input_parameter< t_effects >::type effects(effectsSEXP);
    Rcpp::traits::input_parameter< const int >::type n_gam(n_gamSEXP);
    Rcpp::traits::input_parameter< const double >::type se_level(se_levelSEXP);
    Rcpp::traits::input_parameter< const int >::type min_rep(min_repSEXP);
    Rcpp::traits::input_parameter< const int >::type max_rep(max_repSEXP);
    Rcpp::traits::input_parameter< const int >::type m(mSEXP);
    Rcpp::traits::input_parameter< const double >::type p(pSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(embv(individual, positions, effects, n_gam, se_level, min_rep, max_rep, m, p, seed));
    return rcpp_result_gen;
END_RCPP
}
// dhbv
Rcpp::NumericVector dhbv(t_individual individual, t_positions positions, t_effects effects, const unsigned int n_rep, const unsigned int m, const double p, Rcpp::Nullable<Rcpp::IntegerVector> seed);
RcppExport SEXP embvr_dhbv(SEXP individualSEXP, SEXP positionsSEXP, SEXP effectsSEXP, SEXP n_repSEXP, SEXP mSEXP, SEXP pSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< t_individual >::type individual(individualSEXP);
    Rcpp::traits::input_parameter< t_positions >::type positions(positionsSEXP);
    Rcpp::traits::input_parameter< t_effects >::type effects(effectsSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type n_rep(n_repSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type m(mSEXP);
    Rcpp::traits::input_parameter< const double >::type p(pSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(dhbv(individual, positions, effects, n_rep, m, p, seed));
    return rcpp_result_gen;
END_RCPP
}
