# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname bcgv
bcgv <- function(individual, positions, locus_effects, n_gam, se_level, min_rep, max_rep, m, p) {
    .Call('bcgvr_bcgv', PACKAGE = 'bcgvr', individual, positions, locus_effects, n_gam, se_level, min_rep, max_rep, m, p)
}

