# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname embv
embv <- function(individual, positions, effects, n_gam, se_level, min_rep, max_rep, m = 0L, p = 1.0, seed = NULL) {
    .Call('embvr_embv', PACKAGE = 'embvr', individual, positions, effects, n_gam, se_level, min_rep, max_rep, m, p, seed)
}

#' @rdname dhbv
dhbv <- function(individual, positions, effects, n_rep, m = 0L, p = 1.0, seed = NULL) {
    .Call('embvr_dhbv', PACKAGE = 'embvr', individual, positions, effects, n_rep, m, p, seed)
}

